### ISSUE TITLE
Build an older version for php8.1.22 and 8.2.9

### ISSUE THREAD

**Issue by henry11996** [Namoshek/docker-php-mssql#11]
Relate to this issue: https://github.com/microsoft/msphpsql/pull/1468

**Comment by Namoshek** [comment]
Publishing additional images for these versions would require quite a bit of duplication. I'll see what I can do in the evening though. Maybe I can publish two images manually to counter this issue.

**Comment by henry11996** [comment]
Regardless of the result, thank you for providing such a convenient image.

**Comment by Namoshek** [comment]
I think the `8.1-*` images provided by this repository are not affected, but only because the upstream tag used by these images has not been updated since PHP 8.1.13. I'll need to change that, although it might cause breaking changes for some users.

The `8.2-*` images are indeed affected though and I'm working on providing images for the `8.1.21-*` and `8.2.8-*` tags. They will be based on Debian Bookworm and Alpine 3.18 though, since these versions are not available for the older distributions of those operating systems.

**Comment by Namoshek** [comment]
The build is currently running (https://github.com/Namoshek/docker-php-mssql/actions/runs/5929621075). It will publish equal images as there are available normally, but with the exact versions `8.1.21-*` and `8.2.8-*`. Please be aware that these images are based on newer Debian and Alpine versions and include newer `msodbcsql` and `nodejs` versions.
