### ISSUE TITLE
Image with apache  #question

### ISSUE THREAD

**Issue by eldelga** [Namoshek/docker-php-mssql#4]
How can I make the image works with apache?

Thanks a lot!

**Comment by Namoshek** [comment]
The configuration of reverse proxies is out of scope for this repository. The only tip I can give you is that you'll need a second container with Apache (or any other reverse proxy) which should proxy requests to the php-fpm container at port 9000, because `mod_php` is not supported by any of the images provided here. Alternatively, you can also look at the Dockerfiles in this repository and build your own image with `php:<version>-apache` as upstream.

**Comment by eldelga** [comment]
Thanks a lot for your quick answer !
