### ISSUE TITLE
php:8.2-cli-bullseye build error

### ISSUE THREAD

**Issue by paulmypo** [Namoshek/docker-php-mssql#7]
![image](https://user-images.githubusercontent.com/108743853/227484011-04ee8c3d-5a45-48e2-9abe-8c70b1d144be.png)

**Comment by Namoshek** [comment]
Thank you for bringing this to my attention! I've not had set up the build notifications for this repository, so I wouldn't have noticed otherwise.

A quick search yields [this issue](https://github.com/microsoft/linux-package-repositories/issues/39), but as this was closed yesterday, I'm a bit confused. Will have to look into it...
